# Generated by Django 4.2.23 on 2025-07-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacao',
            options={'verbose_name': 'Operação', 'verbose_name_plural': 'Operações'},
        ),
        migrations.AddField(
            model_name='operacao',
            name='parametros_exibicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
